export enum PaymentMethod {
  DEFAULT = "-",
  GOPAY = "gopay",
  SHOPEEPAY = "shopeepay",
  QRIS = "qris",
  BCA_VA = "bca_va",
  BNI_VA = "bni_va",
  BRI_VA = "bri_va",
  PERMATA_VA = "permata_va",
  MANDIRI_VA = "echannel",
  INDOMARET = "indomaret",
  ALFAMART = "alfamart",
  CREDIT_CARD = "credit_card",
  AKULAKU = "akulaku",
  KREDIVO = "kredivo",
  DANAMON_ONLINE = "danamon_online",
  CIMB_CLICKS = "cimb_clicks",
  BCA_KLIKBCA = "bca_klikbca",
}
